<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>234dd7b5-2a05-4123-837a-e30fb61767cb</testSuiteGuid>
   <testCaseLink>
      <guid>e90098a4-f43f-454e-809f-4b5dba69bec7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Login feature/TC.Auth.002.001 - User login with valid data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05cab5ec-1000-4d53-b338-95e49f13fb9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a039b04d-0470-4384-aec1-2bcfa21f920e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3d549e1-cf4e-435b-b666-375baf2c27c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Login feature/TC.Auth.002.002 - User login with empty data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46bd9206-0c55-4c7f-a6f5-0e016cb79e9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83623262-0c1d-4a52-adc1-1c94d93aeced</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0bd50e5-a7fc-4af2-a39e-93d27173b396</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Login feature/TC.Auth.002.003 - User register with invalid data email</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc83de14-4e10-4aa9-893a-70119481c42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>294a302f-d077-4a16-b857-88a972eec422</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>07040185-0036-491b-a6da-13c002dff30f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Login feature/TC.Auth.002.004 - User login with password less than 6 character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e74d0e4f-752a-46ea-8af5-2db6fef8627d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f27427d-9caa-47be-9b5d-6f8a4e6a2af6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>322ade3f-7e92-4bb0-9600-f274d4cb4015</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Login feature/TC.Auth.002.005 - User login with invalid data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47daac50-17f6-4e03-a200-f1e6b3d09ffe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>943de3df-8cb5-45f0-8692-d6d89b57db05</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
